#!/usr/bin/python

import os
import sys
import argparse
import time

from novaclient.v1_1 import client

def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument('instances', nargs='*')
    return p.parse_args()

def main():
    opts = parse_args()
    nc = client.Client(os.environ['OS_USERNAME'], os.environ['OS_PASSWORD'],
            os.environ['OS_TENANT_NAME'], os.environ['OS_AUTH_URL'], service_type="compute")

    servers = []
    for s in nc.servers.list():
        if s.name in opts.instances or s.id in opts.instances:
            servers.append(s.id)

    while servers:
        pending = []
        for sid in servers:
            s = nc.servers.get(sid)

            if not s.status == 'ACTIVE':
                pending.append(sid)
            else:
                print '%s is active.' % s.name
        servers = pending
        time.sleep(1)

if __name__ == '__main__':
    main()

